import streamlit as st
import pandas as pd
import requests
import plotly.express as px
import json
import os

API_URL = "http://localhost:8000/api/v1"

st.set_page_config(page_title="Project Risk Manager AI", layout="wide", page_icon="🛡️")

# Inject Custom CSS
css_path = os.path.join(os.path.dirname(__file__), 'style.css')
if os.path.exists(css_path):
    with open(css_path) as f:
        st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

# Inject Subtle Crosshair Cursor
import streamlit.components.v1 as components
components.html(
    """
    <script>
        const parentDoc = window.parent.document;
        let cursor = parentDoc.getElementById('glow-cursor');
        // Remove old cursor elements from previous themes
        if (cursor) cursor.remove();
        let trail = parentDoc.getElementById('cursor-trail');
        if (trail) trail.remove();

        if (!parentDoc.getElementById('cross-cursor')) {
            const style = parentDoc.createElement('style');
            style.innerHTML = `
                .cross-cursor {
                    position: fixed;
                    top: 0; left: 0;
                    width: 24px; height: 24px;
                    pointer-events: none;
                    z-index: 9999999;
                    transform: translate(-50%, -50%);
                    opacity: 0.7;
                    transition: opacity 0.2s;
                }
                .cross-cursor::before, .cross-cursor::after {
                    content: '';
                    position: absolute;
                    background: #1e293b;
                }
                .cross-cursor::before {
                    top: 0; left: 50%;
                    width: 1.5px; height: 100%;
                    transform: translateX(-50%);
                }
                .cross-cursor::after {
                    top: 50%; left: 0;
                    width: 100%; height: 1.5px;
                    transform: translateY(-50%);
                }
                * { cursor: none !important; }
            `;
            parentDoc.head.appendChild(style);

            const cur = parentDoc.createElement('div');
            cur.id = 'cross-cursor';
            cur.className = 'cross-cursor';
            parentDoc.body.appendChild(cur);

            parentDoc.addEventListener('mousemove', e => {
                window.requestAnimationFrame(() => {
                    cur.style.left = e.clientX + 'px';
                    cur.style.top = e.clientY + 'px';
                });
            });
        }
    </script>
    """,
    height=0,
    width=0
)

def load_local_data():
    """Load the mock JSON as the source of truth for the dashboard."""
    data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'sample_data.json')
    with open(data_path, 'r') as f:
        return json.load(f)

def save_local_data(new_data):
    """Save updated data back to the JSON file."""
    data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'sample_data.json')
    with open(data_path, 'w') as f:
        json.dump(new_data, f, indent=2)

data = load_local_data()
projects = data.get("projects", [])

# --- Branded Header ---
import base64

banner_path = os.path.join(os.path.dirname(__file__), 'assets', 'hero_banner.png')
if os.path.exists(banner_path):
    with open(banner_path, 'rb') as img_file:
        banner_b64 = base64.b64encode(img_file.read()).decode()
    st.markdown(f"""
    <div style="text-align:center; margin-bottom: 8px;">
        <img src="data:image/png;base64,{banner_b64}" style="width:100%; max-height:180px; object-fit:cover; border-radius: 12px; opacity:0.85;" />
    </div>
    """, unsafe_allow_html=True)

st.markdown("""
<div style="text-align:center; margin-bottom: 24px;">
    <h1 style="font-family: 'Playfair Display', serif; font-size: 2.4rem; font-weight: 700; color: #0f172a; margin: 0; padding: 0;">AI-Powered Project Risk Management</h1>
    <p style="font-family: 'Inter', sans-serif; font-size: 1rem; color: #64748b !important; margin-top: 8px;">Enterprise-grade risk intelligence for portfolio decision-makers.</p>
    <hr style="border: none; height: 1px; background: linear-gradient(90deg, transparent, #b8860b, transparent); margin: 20px auto; width: 200px;" />
</div>
""", unsafe_allow_html=True)

# --- Dashboard Tabs ---
tab1, tab2, tab3, tab4 = st.tabs(["Portfolio Dashboard", "Agent Reports", "Risk Assistant", "Update Data"])

with tab1:
    st.header("Project Portfolio Health")
    
    with st.expander("ℹ️ How to read this dashboard"):
        st.markdown('''
        * **Risk Score:** A real-time score (0-100) generated by a Machine Learning model assessing budget burn rate, schedule delays, and payment issues.
        * **Green (Low Risk):** Project is healthy and on track.
        * **Orange (Medium Risk):** Warning signs detected, such as minor delays or mild budget overruns.
        * **Red (High Risk):** Project is in distress, e.g., severe payment delays or extreme resource overallocation.
        ''')
    
    st.divider()

    # --- Top Level KPIs ---
    total_budget = sum([p["budget"] for p in projects])
    total_spent = sum([p["spent"] for p in projects])
    active_projects = len(projects)
    
    col_kpi1, col_kpi2, col_kpi3 = st.columns(3)
    with col_kpi1:
        st.metric("Total Active Projects", active_projects)
    with col_kpi2:
        st.metric("Total Portfolio Budget", f"${total_budget:,.2f}")
    with col_kpi3:
        st.metric("Total Spent", f"${total_spent:,.2f}", delta=f"${total_budget - total_spent:,.2f} remaining", delta_color="normal")
        
    st.divider()
    
    # --- Interactive Filtering ---
    st.subheader("Filter Projects")
    all_statuses = list(set([p["status"] for p in projects]))
    selected_statuses = st.multiselect("Filter by Status", all_statuses, default=all_statuses)
    
    filtered_projects = [p for p in projects if p["status"] in selected_statuses]
    
    if not filtered_projects:
        st.warning("No projects match the selected filters.")
    else:
        # --- Charts ---
        st.subheader("Budget Burn Rate Overview")
        df_chart = pd.DataFrame({
            "Project": [p["name"] for p in filtered_projects],
            "Budget": [p["budget"] for p in filtered_projects],
            "Spent": [p["spent"] for p in filtered_projects]
        })
        fig = px.bar(df_chart, x="Project", y=["Budget", "Spent"], barmode="group",
                        color_discrete_map={"Budget": "#1e293b", "Spent": "#b8860b"},
                        title="Budget vs. Spent per Project")
        fig.update_layout(
            plot_bgcolor='#fafafa',
            paper_bgcolor='#ffffff',
            font=dict(family='Inter, sans-serif', color='#334155'),
            title_font=dict(family='Playfair Display, serif', size=18, color='#0f172a'),
            xaxis=dict(gridcolor='#edebe7', color='#64748b'),
            yaxis=dict(gridcolor='#edebe7', color='#64748b'),
            legend=dict(font=dict(color='#64748b')),
            margin=dict(l=20, r=20, t=50, b=20)
        )
        st.plotly_chart(fig, use_container_width=True)
        
        st.divider()

        st.subheader("Project Details")
        metrics_cols = st.columns(len(filtered_projects))
        
        # Calculate fast real-time risk scores via API
        for i, proj in enumerate(filtered_projects):
            try:
                res = requests.post(f"{API_URL}/risk/score", json=proj).json()
                score = res.get("score", 0)
                category = res.get("category", "Unknown")
                
                color = "green" if category == "Low" else "orange" if category == "Medium" else "red"
                
                with metrics_cols[i]:
                    st.markdown(f"### {proj['name']}")
                    st.markdown(f"**Status:** {proj['status']}")
                    st.markdown(f"**Risk Score:** <span style='color:{color}; font-size: 24px'>{score:.1f}/100</span> ({category})", unsafe_allow_html=True)
                    st.progress(proj['completed_tasks'] / proj['total_tasks'], text="Task Completion")
                    st.caption(f"Budget Spent: ${proj['spent']} / ${proj['budget']}")
                    if int(proj['payment_delays_days']) > 0:
                        st.error(f"⚠️ Payment delayed by {proj['payment_delays_days']} days")
                        
            except Exception as e:
                with metrics_cols[i]:
                    st.error(f"API Offline. Start FastAPI server. {e}")

with tab2:
    st.markdown("""
    <div style="margin-bottom:8px;">
        <h2 style="font-family:'Playfair Display',serif; color:#0f172a; font-size:1.8rem; margin:0;">
            🧠 Real-Time IT Project Risk Assessment
        </h2>
        <p style="color:#64748b; font-size:0.95rem; margin-top:4px;">
            Enter your IT project details below. The AI agents will identify, assess, and suggest mitigations for risks in real time.
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    with st.form("realtime_risk_form", clear_on_submit=False):
        # ── Section 1: Project Identity ───────────────────────────────────────
        st.markdown("### 📋 Project Identity")
        col_a, col_b = st.columns(2)
        with col_a:
            rt_name = st.text_input("Project Name *", placeholder="e.g. Cloud ERP Migration")
            rt_tech = st.text_input("Tech Stack", placeholder="e.g. AWS, Kubernetes, Python, PostgreSQL")
        with col_b:
            rt_status = st.selectbox("Project Status", ["In Progress", "On Track", "At Risk", "Blocked", "Completed"])
            rt_employees = st.number_input("Number of Employees / Team Size", min_value=1, max_value=10000, value=10, step=1)

        rt_description = st.text_area(
            "Project Description *",
            placeholder="Briefly describe the IT project scope, objectives, and key deliverables...",
            height=110
        )

        # ── Section 2: Financial Health ────────────────────────────────────────
        st.markdown("### 💰 Financial Health")
        col_f1, col_f2, col_f3 = st.columns(3)
        with col_f1:
            rt_budget = st.number_input("Total Budget ($)", min_value=1000, value=500000, step=10000)
        with col_f2:
            rt_spent = st.number_input("Budget Spent ($)", min_value=0, value=150000, step=5000)
        with col_f3:
            rt_delay = st.number_input("Payment Delay (days)", min_value=0, value=0, step=1)

        # ── Section 3: Schedule & Progress ─────────────────────────────────────
        st.markdown("### 📅 Schedule & Progress")
        col_s1, col_s2, col_s3, col_s4 = st.columns(4)
        with col_s1:
            rt_timeline = st.number_input("Total Timeline (days)", min_value=1, value=180, step=1)
        with col_s2:
            rt_elapsed = st.number_input("Days Elapsed", min_value=0, value=60, step=1)
        with col_s3:
            rt_comp_tasks = st.number_input("Completed Tasks", min_value=0, value=30, step=1)
        with col_s4:
            rt_total_tasks = st.number_input("Total Tasks", min_value=1, value=100, step=1)

        rt_resource_util = st.slider(
            "Resource Utilization (0 = idle, 1.0 = fully allocated, >1.0 = overloaded)",
            min_value=0.0, max_value=2.0, value=0.85, step=0.05,
            format="%.2f"
        )

        # ── Section 4: Market Context ──────────────────────────────────────────
        st.markdown("### 🌐 Market & External Context")
        rt_market = st.text_area(
            "Market / Regulatory Context",
            placeholder="Describe external risks: e.g. 'New GDPR compliance mandate', 'Cloud vendor pricing changes', 'Talent shortage in DevOps'...",
            height=90
        )

        st.divider()
        submitted = st.form_submit_button("🚀 Run Full AI Risk Analysis", use_container_width=True)

    # ── After form submission ─────────────────────────────────────────────────
    if submitted:
        if not rt_name.strip():
            st.error("⚠️ Please enter a Project Name before running the analysis.")
        elif not rt_description.strip():
            st.error("⚠️ Please enter a Project Description before running the analysis.")
        else:
            # Build project payload
            import uuid
            project_payload = {
                "id": f"RT-{uuid.uuid4().hex[:6].upper()}",
                "name": rt_name.strip(),
                "description": rt_description.strip(),
                "tech_stack": rt_tech.strip() or "Not specified",
                "employees": int(rt_employees),
                "status": rt_status,
                "budget": float(rt_budget),
                "spent": float(rt_spent),
                "payment_delays_days": int(rt_delay),
                "timeline_days": int(rt_timeline),
                "days_elapsed": int(rt_elapsed),
                "completed_tasks": int(rt_comp_tasks),
                "total_tasks": int(rt_total_tasks),
                "resource_utilization": float(rt_resource_util),
                "market_context": rt_market.strip() or "General IT Market"
            }

            # ── Step 1: Instant ML Risk Preview ──────────────────────────────
            st.markdown("---")
            st.markdown("### ⚡ Instant ML Risk Preview")
            try:
                ml_res = requests.post(f"{API_URL}/risk/score", json=project_payload, timeout=10).json()
                ml_score = ml_res.get("score", 0)
                ml_cat = ml_res.get("category", "Unknown")
                color = "#22c55e" if ml_cat == "Low" else "#f97316" if ml_cat == "Medium" else "#ef4444"
                budget_pct = (rt_spent / rt_budget * 100) if rt_budget > 0 else 0
                task_pct = (rt_comp_tasks / rt_total_tasks * 100) if rt_total_tasks > 0 else 0
                
                mc1, mc2, mc3, mc4 = st.columns(4)
                mc1.metric("🎯 Risk Score", f"{ml_score:.1f} / 100")
                mc2.metric("🏷️ Risk Category", ml_cat)
                mc3.metric("💸 Budget Consumed", f"{budget_pct:.1f}%")
                mc4.metric("✅ Tasks Completed", f"{task_pct:.1f}%")
                st.markdown(
                    f"<div style='padding:10px 16px; border-radius:8px; background:{color}22; border-left:4px solid {color}; color:{color}; font-weight:600; font-size:1rem;'>"
                    f"Risk Level: {ml_cat}</div>",
                    unsafe_allow_html=True
                )
            except Exception as e:
                st.warning(f"Could not fetch ML preview (API may be offline): {e}")

            # ── Step 2: Full CrewAI Agent Report ─────────────────────────────
            st.markdown("---")
            st.markdown("### 📄 Full AI Agent Report")
            st.info(
                "🤖 The AI agents are now analyzing your project — examining internal health, market sentiment, "
                "computing an ML risk score, and searching historical precedents. This takes 1–3 minutes on a free API tier."
            )
            with st.spinner(f"Agents analyzing **{rt_name}**... Please wait (up to 3 minutes)"):
                try:
                    res = requests.post(
                        f"{API_URL}/agent/report",
                        json=project_payload,
                        timeout=180
                    ).json()

                    if res.get("status") == "success":
                        st.success("✅ Analysis complete!")
                        st.markdown(res.get("report", "No report content returned."))
                        
                        # Download button for the report
                        report_md = res.get("report", "")
                        st.download_button(
                            label="⬇️ Download Report as Markdown",
                            data=report_md,
                            file_name=f"risk_report_{rt_name.replace(' ', '_')}.md",
                            mime="text/markdown"
                        )
                    else:
                        st.error(res.get("detail", "An error occurred during agent execution."))
                except requests.exceptions.Timeout:
                    st.error("⏱️ The agent analysis timed out after 3 minutes. Please try again.")
                except Exception as e:
                    st.error(f"❌ Failed to reach the agent API. Ensure FastAPI is running.\n\nError: {e}")


with tab3:
    st.header("Conversational Risk Assistant")
    st.markdown("Ask natural language questions about project risks, historical mitigations, and current status.")
    
    # Simple Chat UI
    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if prompt := st.chat_input("E.g., What are the mitigation strategies for database migration latency?"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            try:
                # Provide contexts of all projects to Chatbot
                context = json.dumps(projects)
                payload = {"query": prompt, "context": context}
                res = requests.post(f"{API_URL}/chat", json=payload).json()
                reply = res.get("reply", "No response.")
                st.markdown(reply)
                st.session_state.messages.append({"role": "assistant", "content": reply})
            except Exception as e:
                error_msg = f"Failed to connect to Chatbot API: {e}"
                st.error(error_msg)
                st.session_state.messages.append({"role": "assistant", "content": error_msg})

with tab4:
    st.header("Update Project Data")
    st.markdown("Use this form to dynamically update project metrics. Changes will be saved to the database and reflected on the dashboard immediately.")
    
    edit_proj_name = st.selectbox("Select Project to Update", [p["name"] for p in projects])
    edit_proj = next(p for p in projects if p["name"] == edit_proj_name)
    
    with st.form("update_project_form"):
        st.subheader(f"Editing: {edit_proj['name']}")
        
        col1, col2 = st.columns(2)
        with col1:
            new_status = st.selectbox("Status", ["On Track", "In Progress", "At Risk", "Blocked", "Completed"], index=["On Track", "In Progress", "At Risk", "Blocked", "Completed"].index(edit_proj["status"]) if edit_proj["status"] in ["On Track", "In Progress", "At Risk", "Blocked", "Completed"] else 0)
            new_spent = st.number_input("Budget Spent ($)", min_value=0, value=edit_proj["spent"])
            new_completed = st.number_input("Completed Tasks", min_value=0, value=edit_proj["completed_tasks"])
        with col2:
            new_util = st.slider("Resource Utilization", 0.0, 1.5, float(edit_proj["resource_utilization"]))
            new_delays = st.number_input("Payment Delays (Days)", min_value=0, value=int(edit_proj["payment_delays_days"]))
            
        submit_button = st.form_submit_button(label="Save Updates")
        
        if submit_button:
            # Find and update the project in the main data dictionary
            for p in data["projects"]:
                if p["id"] == edit_proj["id"]:
                    p["status"] = new_status
                    p["spent"] = new_spent
                    p["completed_tasks"] = new_completed
                    p["resource_utilization"] = new_util
                    p["payment_delays_days"] = new_delays
                    break
            
            # Save the updated data
            try:
                save_local_data(data)
                st.success(f"Project '{edit_proj['name']}' updated successfully!")
                # Force a rerun to refresh the dashboard tab
                st.rerun()
            except Exception as e:
                st.error(f"Failed to save data: {e}")
